name: build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x build.sh && ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: SRDebuggerEnabler
          path: SRDebuggerEnabler.dylib
